spring:
  profiles:
    active: test

server:
  port: 18088

user:
  admin:
    username: admin
    password: admin@bm123

auth:
  api:
    excludes:
      - /api/kms-center/pull/
      - /api/config-center/encrypt/download/
#      - /api/config-center/encrypt/shuffleV2/