spring:
  profiles:
    active: test-docker

server:
  port: 18088

user:
  admin:
    username: admin
    password: admin


mybatis-plus:
  typeEnumsPackage: cn.com.bluemoon.daps.*.enums
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: id_worker_str
  # 扫描 mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  configuration:
    jdbc-type-for-null: 'null'