create table ds_sys_sensitive_shuffle_info
(
    id                         bigint auto_increment comment '主键id字段'
        primary key,
    schema_name                varchar(50)                            not null,
    table_name                 varchar(100)                           not null comment '表名',
    incr_field_name            varchar(100)                           null comment '表增量字段，默认为无，全量刷表数据；若有，则指定最多一个增量字段，进行增量刷库；若一个表定义多个增量字段则取只其中一个',
    on_update_timestamp_fields varchar(225) default ''                null comment '表onUpdate时间戳的列表，多个用英文逗号隔开',
    create_time                timestamp    default CURRENT_TIMESTAMP null comment '创建时间',
    update_time                timestamp                              null on update CURRENT_TIMESTAMP comment '更新数据'
)
    comment '数据安全系统敏感-洗数信息';

INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (501, 'ec_order', 'ec_oms_order', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (502, 'ec_order', 'ec_oms_plat_order_encrypt_data', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (503, 'ec_order', 'ec_oms_order_import', 'order_import_time', ' ', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (504, 'ec_order', 'ec_oms_invoice', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (505, 'ec_order', 'ec_oms_plat_order_decrypt_data', 'decrypt_time', ' ', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (506, 'ec_order', 'ec_oms_sms_management_sub', 'create_time', ' ', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (507, 'ec_order', 'ec_oms_plat_tmall_presale_order', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (508, 'ec_order', 'ec_oms_sms_management', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (509, 'ec_order', 'ec_oms_plat_address_modify_record', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (510, 'ec_order', 'ec_oms_exc_reissue_order', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (511, 'ec_order', 'ec_oms_address_modify_record', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (512, 'ec_order', 'ec_oms_address_clean_record', 'create_time', ' ', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (513, 'ec_order', 'oms_b2b_oper_client_base', 'changed_time', 'changed_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (514, 'ec_order', 'oms_b2b_oper_client_account', 'id', ' ', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (515, 'ec_order', 'ec_oms_self_help_query_log', 'create_time', ' ', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (516, 'ec_order', 'sys_user', 'op_time', 'op_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (517, 'ec_order', 'oms_b2b_client_storehouse', 'changed_time', 'changed_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (518, 'ec_order', 'ec_oms_exc_offline_refund_order', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (519, 'ec_order', 'ec_oms_channel_shop_base', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (520, 'ec_order', 'oms_b2b_client_distri_channel_charge', 'changed_time', 'changed_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (521, 'ec_order_test', 'ec_oms_order', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (522, 'ec_order_test', 'ec_oms_plat_order_encrypt_data', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (523, 'ec_order_test', 'ec_oms_order_import', 'order_import_time', ' ', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (524, 'ec_order_test', 'ec_oms_invoice', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (525, 'ec_order_test', 'ec_oms_plat_order_decrypt_data', 'decrypt_time', ' ', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (526, 'ec_order_test', 'ec_oms_sms_management_sub', 'create_time', ' ', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (527, 'ec_order_test', 'ec_oms_plat_tmall_presale_order', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (528, 'ec_order_test', 'ec_oms_sms_management', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (529, 'ec_order_test', 'ec_oms_plat_address_modify_record', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (530, 'ec_order_test', 'ec_oms_exc_reissue_order', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (531, 'ec_order_test', 'ec_oms_address_modify_record', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:55');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (532, 'ec_order_test', 'ec_oms_address_clean_record', 'create_time', ' ', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (533, 'ec_order_test', 'oms_b2b_oper_client_base', 'changed_time', 'changed_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (534, 'ec_order_test', 'oms_b2b_oper_client_account', 'id', ' ', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (535, 'ec_order_test', 'ec_oms_self_help_query_log', 'create_time', ' ', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (536, 'ec_order_test', 'sys_user', 'op_time', 'op_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (537, 'ec_order_test', 'oms_b2b_client_storehouse', 'changed_time', 'changed_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (538, 'ec_order_test', 'ec_oms_exc_offline_refund_order', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (539, 'ec_order_test', 'ec_oms_channel_shop_base', 'last_update_time', 'last_update_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');
INSERT INTO data_asset_platform.ds_sys_sensitive_shuffle_info (id, schema_name, table_name, incr_field_name, on_update_timestamp_fields, create_time, update_time) VALUES (540, 'ec_order_test', 'oms_b2b_client_distri_channel_charge', 'changed_time', 'changed_time', '2022-02-28 09:04:48', '2022-02-28 13:37:56');