centerConfigs:
  - activated: false
    digest: ''
    instanceType: Zookeeper
    name: 电商ec_order测试
    namespace: data_security_ns_test
    orchestrationName: data_security_ns_test
    orchestrationType: config_center
    props: {}
    serverLists: 192.168.243.34:12181
  - activated: true
    digest: ''
    instanceType: Zookeeper
    name: 小屋系统-测试
    namespace: small_room_name_space
    orchestrationName: small_room_name_space
    orchestrationType: config_center
    props: {}
    serverLists: 192.168.243.20:12181,192.168.243.21:12181,192.168.243.22:12181
  - activated: false
    digest: ''
    instanceType: Zookeeper
    name: 本地测试
    namespace: ds_test
    orchestrationName: ds_test
    orchestrationType: config_center
    props: {}
    serverLists: 192.168.243.20:12181,192.168.243.21:12181,192.168.243.22:12181
