alter table bm_ucm_yz_customer add  index idx_mobile(mobile_cipher);
alter table scrm_msg_send_record add  index idx_mobile(mobile_cipher);
alter table bm_ucm_customer_buy_order_info_1 add  index idx_mobile(mobile_cipher);
alter table bm_ucm_customer_call_info add  index idx_mobile(mobile_cipher);
alter table bm_ucm_customer_buy_order_info_3 add  index idx_mobile(mobile_cipher);
alter table bm_ucm_customer_buy_order_info_2 add  index idx_mobile(mobile_cipher);
alter table bm_ucm_customer_address_2 add  index idx_mobile(mobile_cipher);
alter table bm_ucm_customer_address_3 add  index idx_mobile(mobile_cipher);
alter table bm_ucm_customer_buy_info_3 add  index idx_mobile(mobile_cipher);
alter table bm_ucm_customer_address_1 add  index idx_mobile(mobile_cipher);
alter table bm_ucm_customer_import add  index idx_mobile(mobile_cipher);
alter table bm_ucm_customer_buy_info_1 add  index idx_mobile(mobile_cipher);
alter table bm_ucm_customer_buy_info_2 add index idx_mobile(mobile_cipher);
alter table bm_ucm_wxwork_import_record add  index idx_mobile(mobile_cipher);
alter table bm_ucm_jd_membership_info add  index idx_user_mobile(user_mobile_cipher);
alter table bm_ucm_wxwork_mobile add UNIQUE index unq_wci_mobile(wxwork_customer_id, mobile_cipher);
alter table bm_ucm_wxwork_customer_follow_user add  index idx_follow_user_remark_mobiles(follow_user_remark_mobiles_cipher);
alter table bm_ucm_customer_3 add  index idx_name(name_cipher);
alter table bm_ucm_customer_3 add  index idx_phone(phone_cipher);
alter table bm_ucm_customer_3 add UNIQUE index mobile(mobile_cipher);
alter table bm_ucm_customer_1 add  index idx_name(name_cipher);
alter table bm_ucm_customer_1 add  index idx_phone(phone_cipher);
alter table bm_ucm_customer_1 add UNIQUE index mobile(mobile_cipher);
alter table bm_ucm_customer_2 add  index idx_name(name_cipher);
alter table bm_ucm_customer_2 add  index idx_phone(phone_cipher);
alter table bm_ucm_customer_2 add UNIQUE index mobile(mobile_cipher);
