alter table bm_ucm_customer_1 add column address_plain varchar(255) comment '常用详细地址';
alter table bm_ucm_customer_1 add column other_contact_num_plain varchar(32) comment '客户其他号码';
alter table bm_ucm_customer_1 add column mobile_plain varchar(20) comment '客户手机';
alter table bm_ucm_customer_1 add column phone_plain varchar(32) comment '客户固话';
alter table bm_ucm_customer_1 add column name_plain varchar(32) comment '客户姓名';
alter table bm_ucm_customer_2 add column mobile_plain varchar(20) comment '客户手机';
alter table bm_ucm_customer_2 add column address_plain varchar(255) comment '常用详细地址';
alter table bm_ucm_customer_2 add column other_contact_num_plain varchar(32) comment '客户其他号码';
alter table bm_ucm_customer_2 add column phone_plain varchar(32) comment '客户固话';
alter table bm_ucm_customer_2 add column name_plain varchar(32) comment '客户姓名';
alter table bm_ucm_customer_3 add column mobile_plain varchar(20) comment '客户手机';
alter table bm_ucm_customer_3 add column phone_plain varchar(32) comment '客户固话';
alter table bm_ucm_customer_3 add column address_plain varchar(255) comment '常用详细地址';
alter table bm_ucm_customer_3 add column other_contact_num_plain varchar(32) comment '客户其他号码';
alter table bm_ucm_customer_3 add column name_plain varchar(32) comment '客户姓名';
alter table bm_ucm_customer_address_1 add column mobile_plain varchar(20) not null  comment '手机号';
alter table bm_ucm_customer_address_1 add column receiver_name_plain varchar(32) comment '收货人姓名';
alter table bm_ucm_customer_address_1 add column address_plain varchar(255) comment '详细地址';
alter table bm_ucm_customer_address_2 add column mobile_plain varchar(20) not null  comment '手机号';
alter table bm_ucm_customer_address_2 add column address_plain varchar(255) comment '详细地址';
alter table bm_ucm_customer_address_2 add column receiver_name_plain varchar(32) comment '收货人姓名';
alter table bm_ucm_customer_address_3 add column address_plain varchar(255) comment '详细地址';
alter table bm_ucm_customer_address_3 add column receiver_name_plain varchar(32) comment '收货人姓名';
alter table bm_ucm_customer_address_3 add column mobile_plain varchar(20) not null  comment '手机号';
alter table bm_ucm_customer_buy_info_1 add column mobile_plain varchar(20) not null  comment '手机号';
alter table bm_ucm_customer_buy_info_2 add column mobile_plain varchar(20) not null  comment '手机号';
alter table bm_ucm_customer_buy_info_3 add column mobile_plain varchar(20) not null  comment '手机号';
alter table bm_ucm_customer_buy_order_info_1 add column mobile_plain varchar(20) not null  comment '手机号';
alter table bm_ucm_customer_buy_order_info_2 add column mobile_plain varchar(20) not null  comment '手机号';
alter table bm_ucm_customer_buy_order_info_3 add column mobile_plain varchar(20) not null  comment '手机号';
alter table bm_ucm_customer_call_info add column mobile_plain varchar(20) not null  comment '手机号';
alter table bm_ucm_customer_import add column mobile_plain varchar(20) comment '客户手机';
alter table bm_ucm_customer_import add column name_plain varchar(32) comment '客户姓名';
alter table bm_ucm_customer_import add column phone_plain varchar(32) comment '客户固话';
alter table bm_ucm_customer_import add column other_contact_num_plain varchar(32) comment '客户其他号码';
alter table bm_ucm_customer_import add column address_plain varchar(255) comment '常用详细地址';
alter table bm_ucm_customer_oper_log_1 add column masking_plain varchar(255) comment '记录内容需要脱敏的内容，多个值之间用逗号隔开';
alter table bm_ucm_customer_oper_log_2 add column masking_plain varchar(255) comment '记录内容需要脱敏的内容，多个值之间用逗号隔开';
alter table bm_ucm_customer_oper_log_3 add column masking_plain varchar(255) comment '记录内容需要脱敏的内容，多个值之间用逗号隔开';
alter table bm_ucm_jd_membership_info add column address_plain varchar(255) comment '详细地址';
alter table bm_ucm_jd_membership_info add column user_mobile_plain varchar(64) comment '手机';
alter table bm_ucm_member_cy_customer add column mobile_plain varchar(20) comment '手机号';
alter table bm_ucm_member_wx_user add column mobile_plain varchar(20) comment '电话，可包含区号';
alter table bm_ucm_wxwork_customer add column mobile_plain varchar(20) not null  comment '手机号';
alter table bm_ucm_wxwork_customer_follow_user add column follow_user_remark_mobiles_plain varchar(128) comment '客服备注手机号，多个逗号分隔';
alter table bm_ucm_wxwork_import_record add column mobile_plain varchar(64) comment '手机号码';
alter table bm_ucm_wxwork_mobile add column mobile_plain varchar(20) not null  comment '手机号';
alter table bm_ucm_wxwork_mobile_history add column mobile_plain varchar(20) not null  comment '手机号';
alter table bm_ucm_yz_customer add column mobile_plain varchar(20) comment '手机号';
alter table bm_ucm_yz_customer_import add column mobile_plain varchar(20) comment '手机号';
alter table scrm_crowd_data add column mobile_plain varchar(20) not null  comment '手机号码';
alter table scrm_marketing_activity_user add column mobile_plain varchar(20) comment '手机号码';
alter table scrm_msg_send_record add column mobile_plain varchar(20) not null  comment '手机号码';
alter table scrm_white_list_import add column mobile_plain varchar(20) comment '手机号码';
