alter table ec_oms_address_clean_record add column address_plain varchar(255) not null  comment '收货人详细地址';
alter table ec_oms_address_modify_record add column receiver_name_plain varchar(32) default '' not null  comment '收货人姓名';
alter table ec_oms_address_modify_record add column address_plain varchar(255) comment '收货人详细地址';
alter table ec_oms_address_modify_record add column receiver_mobile_plain varchar(20) comment '收货人手机';
alter table ec_oms_channel_shop_base add column shop_password_plain varchar(100) not null  comment '店铺密码';
alter table ec_oms_channel_shop_base add column shop_phone_number_plain varchar(15) not null  comment '店铺绑定手机';
alter table ec_oms_exc_offline_refund_order add column account_name_plain varchar(20) comment '账户名称';
alter table ec_oms_exc_offline_refund_order add column account_plain varchar(64) comment '账户（支付宝）';
alter table ec_oms_exc_reissue_order add column receiver_mobile_plain varchar(20) not null  comment '补发收货人手机';
alter table ec_oms_exc_reissue_order add column receiver_name_plain varchar(32) not null  comment '补发收货人姓名';
alter table ec_oms_exc_reissue_order add column address_plain varchar(255) not null  comment '补发详细地址';
alter table ec_oms_invoice add column buyer_address_plain varchar(128) comment '购买方地址';
alter table ec_oms_invoice add column invoice_receiver_phone_plain varchar(20) comment '收票人手机';
alter table ec_oms_invoice add column buyer_bank_account_plain varchar(128) comment '购买方开户行帐号';
alter table ec_oms_invoice add column invoice_receiver_address_plain varchar(255) comment '收票地址';
alter table ec_oms_invoice add column invoice_receiver_plain varchar(32) comment '收票人';
alter table ec_oms_order add column receiver_mobile_plain varchar(20) comment '收货人手机';
alter table ec_oms_order add column address_plain varchar(255) comment '收货人详细地址';
alter table ec_oms_order add column receiver_name_plain varchar(32) default '' not null  comment '收货人姓名';
alter table ec_oms_order_import add column address_plain varchar(255) comment '收货人详细地址';
alter table ec_oms_order_import add column receiver_name_plain varchar(32) default '' not null  comment '收货人姓名';
alter table ec_oms_order_import add column receiver_mobile_plain varchar(20) comment '收货人手机';
alter table ec_oms_plat_address_modify_record add column receiver_name_plain varchar(32) default '' not null  comment '收货人姓名';
alter table ec_oms_plat_address_modify_record add column receiver_phone_plain varchar(32) comment '收货人电话';
alter table ec_oms_plat_address_modify_record add column address_plain varchar(255) comment '收货人详细地址';
alter table ec_oms_plat_order_decrypt_data add column address_decrypted_plain varchar(255) comment '地址明文';
alter table ec_oms_plat_order_decrypt_data add column receiver_mobile_decrypted_plain varchar(20) comment '收件人手机明文';
alter table ec_oms_plat_order_decrypt_data add column receiver_name_decrypted_plain varchar(32) comment '收件人明文';
alter table ec_oms_plat_order_encrypt_data add column address_decrypted_plain varchar(255) comment '地址明文';
alter table ec_oms_plat_order_encrypt_data add column receiver_mobile_decrypted_plain varchar(20) comment '收件人手机明文';
alter table ec_oms_plat_order_encrypt_data add column receiver_name_decrypted_plain varchar(32) comment '收件人明文';
alter table ec_oms_plat_tmall_presale_order add column receiver_name_plain varchar(32) default '' not null  comment '收货人姓名';
alter table ec_oms_plat_tmall_presale_order add column address_plain varchar(255) comment '收货人详细地址';
alter table ec_oms_plat_tmall_presale_order add column receiver_mobile_plain varchar(32) comment '收货人手机';
alter table ec_oms_self_help_query_log add column receiver_mobile_plain varchar(20) default '' not null  comment '收货人手机号码';
alter table ec_oms_sms_management add column receive_name_plain varchar(32) comment '收货人姓名';
alter table ec_oms_sms_management add column phone_number_plain varchar(20) not null  comment '手机号码';
alter table ec_oms_sms_management_sub add column phone_number_plain varchar(20) not null  comment '手机号码';
alter table ec_oms_sms_management_sub add column receive_name_plain varchar(32) comment '收货人姓名';
alter table oms_b2b_client_distri_channel_charge add column charge_phone_plain varchar(20) not null  comment '负责人电话';
alter table oms_b2b_client_storehouse add column charge_phone_plain varchar(20) not null  comment '负责人电话';
alter table oms_b2b_oper_client_account add column account_card_plain varchar(100) comment '付款/收款账号';
alter table oms_b2b_oper_client_base add column client_name_plain varchar(50) comment '客户姓名';
alter table oms_b2b_oper_client_base add column invoice_account_plain varchar(100) comment '开票银行账号';
alter table oms_b2b_oper_client_base add column company_address_plain varchar(255) comment '公司详细地址';
alter table oms_b2b_oper_client_base add column charge_phone_plain varchar(50) comment '负责人电话';
alter table oms_b2b_oper_client_base add column receive_invoice_address_plain varchar(255) comment '收票详细地址';
alter table oms_b2b_oper_client_base add column mobile_phone_plain bigint(20) comment '手机号码';
alter table oms_b2b_oper_client_base add column receive_invoice_name_plain varchar(50) comment '收票人姓名';
alter table oms_b2b_oper_client_base add column receive_invoice_phone_plain varchar(50) comment '收票人电话';
alter table sys_user add column mobile_plain varchar(36) comment '手机';
